FancyBlog/config/routes.rb
Blog::Application.routes.draw do
  root 'welcome#index'
  resources :posts do
    resources :comments, :only => [:create, :destroy]
  end

  get 'tags/:tag', to: 'posts#index', as: :tag
  resources :posts

end

FancyBlog/app/models/comment.rb
class Comment < ActiveRecord::Base
	attr_accessible :body

	belongs_to :post
end

FancyBlog/app/models/post.rb
class Post < ActiveRecord::Base
  	acts_as_taggable
  	attr_accessible :title, :body, :tag_list, :comments

	has_many :comments
end

FancyBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

FancyBlog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create!(params.require(:comment).permit!)
        redirect_to @post
    end

	# DELETE /comments/1
  	# DELETE /commentss/1.json
    def destroy
      @post = Post.find(params[:post_id])
      @comment = Comment.find(params[:id])
    	@comment.destroy
   		respond_to do |format|
      		format.html { redirect_to @post }
      		format.json { head :no_content }
    	end
  	end

    def comment_params
    	 params.require(:comment).permit(:body)
    end
end

FancyBlog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate, :except => [ :index, :show ]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :tag]



  # GET /posts
  # GET /posts.json
  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :tag_list, :comments)
    end

  private
  def authenticate
    authenticate_or_request_with_http_basic do |name, password|
      name == "admin" && password == "secret"
    end
  end 
end

FancyBlog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

FancyBlog/app/helpers/application_helper.rb
module ApplicationHelper
end

FancyBlog/app/helpers/comments_helper.rb
module CommentsHelper
end

FancyBlog/app/helpers/posts_helper.rb
module PostsHelper
end

FancyBlog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

FancyBlog/app/views/comments/_comment.html.erb
<%= div_for comment do %>
    <p>
        <span class="glyphicon glyphicon-comment"> </span><strong> Posted <%= time_ago_in_words(comment.created_at) %> ago</strong>
        <div><%= comment.body %></div>
        <%= link_to 'Delete', post_comment_path(@post, comment), method: :delete, :confirm => 'Are you sure?' %>
    </p>
    
<% end %>

FancyBlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag 'blogStyle' %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

FancyBlog/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <div class="blackText"><%= f.text_field :title %></div>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <div class="blackText"><%= f.text_area :body %></div>
  </div>
  <div class="field">
  <%= f.label :tag_list, "Tags (separated by commas)" %><br />
  <div class="blackText"><%= f.text_field :tag_list %></div>
  </div>
  <div class="actions blackText">
    <%= f.submit %>
  </div>
<% end %>

FancyBlog/app/views/posts/_post.html.erb
<div class="padded">
<h2><%= link_to_unless_current post.title, post %></h2>
<div class="postBody col-md-5">
	<div class="padded">
		<%= simple_format post.body %>
	</div>
</div>
<div class="clear"></div>
<div class="padded"><span class="glyphicon glyphicon-tags"> Tags: </span> <%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')%></div>
<!--<div>Tags: <%= post.tag_list %>-->
<div class="clear"></div>
	<tr>
	    <!--<td><%= link_to 'Show', post %></td>-->
	    <td><%= link_to 'Edit', edit_post_path(post) %></td> | 
	    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td> | 
	    <td><%= link_to 'Back', posts_path %></td>
	</tr>
</div>

FancyBlog/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<div class="clear padded"></div>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

FancyBlog/app/views/posts/index.html.erb
<!--<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>-->
<h1 class="padded">Listing posts</h1>

<%= render :partial => @posts %>

<div class="clear padded"></div>

<div class="padded"><%= link_to 'New Post', new_post_path %>

<div class="clear padded"></div>

<%= link_to 'Back', root_path %></div>

FancyBlog/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<div class="clear padded"></div>

<%= link_to 'Back', posts_path %>

FancyBlog/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= render :partial => @post %>

<div class="clear padded"></div>

<h3>Comments</h3>
<div id="comments">
    <%= render :partial => @post.comments %>
</div>

<%= form_for [@post, Comment.new] do |f| %>
        <p>
            <%= f.label :label, "New comment" %>
            <div class="clear"></div>
            <div class="blackText"><%= f.text_area :body %></div>
        </p>
        <p class="blackText"><%= f.submit "Add comment" %></p>
<% end %>
</div>


<!--<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>-->

FancyBlog/app/views/welcome/index.html.erb
<div class="row">
	<div class="col-md-4"></div>
	<div class="welcome center col-md-4">
		<h1 class="padded">Welcome to the Fancy Blog</h1>
		<p>Allows CRUD operations, authentication, tagging plus search by tag, and comments. Features styling via Twitter Bootstrap.</p>
		<p>Perfect for an IT 232 final project.</p>
		<div class="clear padded"></div>
		<%= link_to ' Continue to blog...', posts_path, class: "glyphicon glyphicon-chevron-right padded" %>
	</div>
	<div class="col-md-4"></div>
</div>
<div class="clear"></div>